# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS uv

# Set the working directory
WORKDIR /app

# Copy the project files
COPY . .

# Install the project's dependencies using uv
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev --no-editable

# Use a separate stage for the runtime environment
FROM python:3.12-slim-bookworm

# Set the working directory
WORKDIR /app

# Copy the virtual environment from the build stage
COPY --from=uv /root/.local /root/.local
COPY --from=uv --chown=app:app /app/.venv /app/.venv

# Set the environment path
ENV PATH="/app/.venv/bin:$PATH"

# Use an env file or set environment variables for email configuration
# ENV EMAIL_ADDRESS=your.email@gmail.com
# ENV EMAIL_PASSWORD=your-app-specific-password
# ENV IMAP_SERVER=imap.gmail.com
# ENV SMTP_SERVER=smtp.gmail.com
# ENV SMTP_PORT=587

# Set the entrypoint to the email-client script
ENTRYPOINT ["email-client"]
